name: prod Runner

on: workflow_dispatch

jobs:
  deployment:
    environment: prod
    runs-on: ubuntu-latest
    container: node:16-alpine
    
    steps:
    - name: Checking out repo...
      uses: actions/checkout@v3
      with:
        ref: prod
    
    - name: Building...
      uses: ./.github/actions/prod-build
      with:
        SERVICE_ACCOUNT_KEYFILE_JSON: ${{ secrets.SERVICE_ACCOUNT_KEYFILE_JSON }}
        ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
        ARTIFACTORY_PASS: ${{ secrets.ARTIFACTORY_PASS }}
    
    - name: Deploying...
      uses: ./.github/actions/prod-deploy
      with:
        CLOUD_RUN_DEFAULT_SERVICE_ACCOUNT: ${{ secrets.CLOUD_RUN_DEFAULT_SERVICE_ACCOUNT }}
